# node-ui-example/docker-compose.e2e.yml

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app              # important: make DNS name stable
    environment:
      - PORT=3000
    ports:
      - "3000:3000"                  # optional (useful for curl from host)
