name: "CI — Node API Example"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  node-ci:
    # Reuse shared Node template from .github repo
    uses: BrikByte-Studios/.github/.github/workflows/template-node-ci.yml@main
    with:
      node-version: "20"
