name: "Example: dotnet ci (Build + unit test)"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-dotnet.yml@main
    with:
      working_directory: "dotnet-api-example"
      runtime_version: ""               # or "20" if you want explicit
      run_lint: true
      run_tests: true
      lint_command: "make lint"
      test_command: "make test"
      build_command: "make build"
      upload_artifacts: true
      artifact_paths: "TestResults/**,out/**,**/bin/**,**/obj/**"

  unit-tests:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/unit-test-dotnet.yml@main
    with:
      working_directory: "dotnet-api-example"
      dotnet_version: "8.0.x"
      test_command: "make test"
      coverage_mode: "optional"
      enforcement_mode: "warn"
