name: "E2E - Cypress (node-ui-example)"

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - "node-ui-example/**"
      - ".github/workflows/e2e-cypress-demo.yml"
  push:
    branches: [ main ]
    paths:
      - "node-ui-example/**"
      - ".github/workflows/e2e-cypress-demo.yml"

jobs:
  e2e-cypress:
    uses: BrikByte-Studios/.github/.github/workflows/e2e-cypress.yml@main
    with:
      start_with_docker: true
      docker_image_name: node-ui-example-app
      docker_port: 3000
      target_url: "http://app:3000"
      health_path: "/health"
      service_workdir: "node-ui-example"
      cypress_image: "cypress/included:13.12.0"
