name: "Example: go build"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-go.yml@main
    with:
      working_directory: "go-api-example"
      run_lint: false
      run_tests: true
      upload_artifacts: true