name: "Example: java build"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-java.yml@main
    with:
      working_directory: "java-api-example"
      runtime_version: ""               # or "20" if you want explicit
      run_lint: true
      run_tests: true
      lint_command: "make lint"
      test_command: "make test"
      build_command: "make build"
      upload_artifacts: true
      artifact_paths: "target/**,out/**"

  unit-tests:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/unit-test-java.yml@main
    with:
      working_directory: "java-api-example"
      java_version: "17"
      build_tool: "maven"
      test_command: "make test"
      coverage_mode: "optional"
      enforcement_mode: "warn"
