name: "Example: java build"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-java.yml@main
    with:
      working_directory: "java-api-example"
      run_lint: false
      run_tests: true
      upload_artifacts: true
