name: "Example: node ci (Build + unit test)"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-node.yml@main
    with:
      working_directory: "node-api-example"
      runtime_version: ""               # or "20" if you want explicit
      run_lint: true
      run_tests: true
      lint_command: "make lint"
      test_command: "make test"
      build_command: "make build"
      upload_artifacts: true
      artifact_paths: "dist/**,coverage/**,out/**"

  unit-tests:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/unit-test-node.yml@main
    with:
      working_directory: "node-api-example"
      node_version: "20"
      package_manager: "npm"
      test_command: "make test"
      coverage_mode: "optional"
      enforcement_mode: "warn"

