name: "Example: python build"

on: [push, pull_request]

jobs:
  build:
    uses: BrikByte-Studios/brik-pipe-actions/.github/workflows/build-python.yml@main
    with:
      working_directory: "python-api-example"
      run_lint: false
      run_tests: true
      upload_artifacts: true